
= Management Schema


This chapter documents the set of *management entity types* that define
configuration and management of a Dispatch Router. A management entity type has
a set of *attributes* that can be read, some attributes can also be
updated. Some entity types also support *operations* that can be called.

All management entity types have the following standard attributes:

type::
  The fully qualified type of the entity,
  e.g. `org.apache.qpid.dispatch.router`. This document uses the short name
  without the `org.apache.qpid.dispatch` prefix e.g. `router`. The dispatch
  tools will accept the short or long name.

name::
  A user-generated identity for the entity.  This can be used in other entities
  that need to refer to the named entity.

identity::
  A system-generated identity of the entity. It includes
  the short type name and some identifying information. E.g. `log/AGENT` or
  `listener/localhost:amqp`

There are two main categories of management entity type.

Configuration Entities::
  Parameters that can be set in the configuration file
  (see `qdrouterd.conf(5)` man page) or set at run-time with the `qdmanage(8)`
  tool.

Operational Entities::
   Run-time status values that can be queried using `qdstat(8)` or `qdmanage(8)` tools.


== Configuration Entities


Configuration entities define the attributes allowed in the configuration file
(see `qdrouterd.conf(5)`) but you can also create entities once the router is
running using the `qdrouterd(8)` tool's `create` operation. Some entities can also
be modified using the `update` operation, see the entity descriptions below.


=== container

(DEPRECATED)Attributes related to the AMQP container. This entity has been deprecated. Use the router entity instead.

Operations allowed: `READ`



'containerName' (string, `CREATE`)::
  The  name of the AMQP container.  If not specified, the container name will be set to a value of the container's choosing.  The automatically assigned container name is not guaranteed to be persistent across restarts of the container.

'workerThreads' (integer, default=4, `CREATE`)::
  The number of threads that will be created to process message traffic and other application work (timers, non-amqp file descriptors, etc.) .

'debugDump' (path, `CREATE`)::
  A file to dump debugging information that can't be logged normally.

'saslConfigPath' (path, `CREATE`)::
  Absolute path to the SASL configuration file.

'saslConfigName' (string, `CREATE`)::
  Name of the SASL configuration.  This string + '.conf' is the name of the configuration file.


=== router

Tracks peer routers and computes routes to destinations.

Operations allowed: `READ`



'routerId' (string, `CREATE`)::
  (DEPRECATED) Router's unique identity. This attribute has been deprecated. Use id instead

'id' (string, `CREATE`)::
  Router's unique identity. One of id or routerId is required. The router will fail to start without id or routerId

'mode' (One of ['standalone', 'interior'], default='standalone', `CREATE`)::
  In standalone mode, the router operates as a single component.  It does not participate in the routing protocol and therefore will not cooperate with other routers. In interior mode, the router operates in cooperation with other interior routers in an interconnected network.

'area' (string)::
  Unused placeholder.

'helloInterval' (integer, default=1, `CREATE`)::
  Interval in seconds between HELLO messages sent to neighbor routers.

'helloMaxAge' (integer, default=3, `CREATE`)::
  Time in seconds after which a neighbor is declared lost if no HELLO is received.

'raInterval' (integer, default=30, `CREATE`)::
  Interval in seconds between Router-Advertisements sent to all routers in a stable network.

'raIntervalFlux' (integer, default=4, `CREATE`)::
  Interval in seconds between Router-Advertisements sent to all routers during topology fluctuations.

'remoteLsMaxAge' (integer, default=60, `CREATE`)::
  Time in seconds after which link state is declared stale if no RA is received.

'mobileAddrMaxAge' (integer, default=60, `CREATE`)::
  (DEPRECATED) This value is no longer used in the router.

'addrCount' (integer)::
  Number of addresses known to the router.

'linkCount' (integer)::
  Number of links attached to the router node.

'nodeCount' (integer)::
  Number of known peer router nodes.

'workerThreads' (integer, default=4, `CREATE`)::
  The number of threads that will be created to process message traffic and other application work (timers, non-amqp file descriptors, etc.) .

'debugDump' (path, `CREATE`)::
  A file to dump debugging information that can't be logged normally.

'saslConfigPath' (path, `CREATE`)::
  Absolute path to the SASL configuration file.

'saslConfigName' (string, default='qdrouterd', `CREATE`)::
  Name of the SASL configuration.  This string + '.conf' is the name of the configuration file.


=== listener

Listens for incoming connections to the router.

Operations allowed: `CREATE`, `DELETE`, `READ`



'addr' (string, default='127.0.0.1', `CREATE`)::
  (DEPRECATED)IP address: ipv4 or ipv6 literal or a host name. This attribute has been deprecated. Use host instead

'host' (string, default='127.0.0.1', `CREATE`)::
  IP address: ipv4 or ipv6 literal or a host name

'port' (string, default='amqp', `CREATE`)::
  Port number or symbolic service name.

'protocolFamily' (One of ['IPv4', 'IPv6'], `CREATE`)::
  ['IPv4', 'IPv6'] IPv4: Internet Protocol version 4; IPv6: Internet Protocol version 6.  If not specified, the protocol family will be automatically determined from the address.

'role' (One of ['normal', 'inter-router', 'route-container', 'on-demand'], default='normal', `CREATE`)::
  The role of an established connection. In the normal role, the connection is assumed to be used for AMQP clients that are doing normal message delivery over the connection.  In the inter-router role, the connection is assumed to be to another router in the network.  Inter-router discovery and routing protocols can only be used over inter-router connections. route-container role can be used for router-container connections, for example, a router-broker connection. on-demand role has been deprecated.

'cost' (integer, default='1', `CREATE`)::
  For the 'inter-router' role only.  This value assigns a cost metric to the inter-router connection.  The default (and minimum) value is one.  Higher values represent higher costs.  The cost is used to influence the routing algorithm as it attempts to use the path with the lowest total cost from ingress to egress.

'certDb' (path, `CREATE`)::
  The absolute path to the database that contains the public certificates of trusted certificate authorities (CA).

'certFile' (path, `CREATE`)::
  The absolute path to the file containing the PEM-formatted public certificate to be used on the local end of any connections using this profile.

'keyFile' (path, `CREATE`)::
  The absolute path to the file containing the PEM-formatted private key for the above certificate.

'passwordFile' (path, `CREATE`)::
  If the above private key is password protected, this is the absolute path to a file containing the password that unlocks the certificate key.

'password' (string, `CREATE`)::
  An alternative to storing the password in a file referenced by passwordFile is to supply the password right here in the configuration file.  This option can be used by supplying the password in the 'password' option.  Don't use both password and passwordFile in the same profile.

'uidFormat' (string, `CREATE`)::
  A list of x509 client certificate fields that will be used to build a string that will uniquely identify the client certificate owner. For e.g. a value of 'cou' indicates that the uid will consist of c - common name concatenated with o - organization-company name concatenated with u - organization unit; or a value of 'o2' indicates that the uid will consist of o (organization name) concatenated with 2 (the sha256 fingerprint of the entire certificate) . Allowed values can be any combination of 'c'( ISO3166 two character country code), 's'(state or province), 'l'(Locality; generally - city), 'o'(Organization - Company Name), 'u'(Organization Unit - typically certificate type or brand), 'n'(CommonName - typically a user name for client certificates) and '1'(sha1 certificate fingerprint, as displayed in the fingerprints section when looking at a certificate with say a web browser is the hash of the entire certificate) and 2 (sha256 certificate fingerprint) and 5 (sha512 certificate fingerprint). 

'displayNameFile' (string, `CREATE`)::
  The absolute path to the file containing the unique id to dispay name mapping

'sslProfileName' (string)::
  The name of the ssl profile. This is for internal use only. Use the 'name' attribute to assign a name to an sslProfile section 

'saslMechanisms' (string, `CREATE`)::
  Space separated list of accepted SASL authentication mechanisms.

'authenticatePeer' (boolean, `CREATE`)::
  yes: Require the peer's identity to be authenticated; no: Do not require any authentication.

'requireEncryption' (boolean, `CREATE`)::
  yes: Require the connection to the peer to be encrypted; no: Permit non-encrypted communication with the peer

'requireSsl' (boolean, `CREATE`)::
  yes: Require the use of SSL or TLS on the connection; no: Allow clients to connect without SSL or TLS.

'trustedCerts' (path, `CREATE`)::
  This optional setting can be used to reduce the set of available CAs for client authentication.  If used, this setting must provide the absolute path to a PEM file that contains the trusted certificates.

'maxFrameSize' (integer, default=16384, `CREATE`)::
  Defaults to 16384.  If specified, it is the maximum frame size in octets that will be used in the connection-open negotiation with a connected peer.  The frame size is the largest contiguous set of uninterrupted data that can be sent for a message delivery over the connection. Interleaving of messages on different links is done at frame granularity.

'idleTimeoutSeconds' (integer, default=16, `CREATE`)::
  The idle timeout, in seconds, for connections through this listener.  If no frames are received on the connection for this time interval, the connection shall be closed.

'requirePeerAuth' (boolean, `CREATE`)::
  (DEPRECATED) This attribute is now controlled by the authenticatePeer attribute.

'allowUnsecured' (boolean, `CREATE`)::
  (DEPRECATED) This attribute is now controlled by the requireEncryption attribute.

'allowNoSasl' (boolean, `CREATE`)::
  (DEPRECATED) This attribute is now controlled by the authenticatePeer attribute.

'stripAnnotations' (One of ['in', 'out', 'both', 'no'], default='both', `CREATE`)::
  ['in', 'out', 'both', 'no'] in: Strip the dispatch router specific annotations only on ingress; out: Strip the dispatch router specific annotations only on egress; both: Strip the dispatch router specific annotations on both ingress and egress; no - do not strip dispatch router specific annotations

'linkCapacity' (integer, `CREATE`)::
  The capacity of links within this connection, in terms of message deliveries.  The capacity is the number of messages that can be in-flight concurrently for each link.


=== connector

Establishes an outgoing connection from the router.

Operations allowed: `CREATE`, `DELETE`, `READ`



'addr' (string, default='127.0.0.1', `CREATE`)::
  (DEPRECATED)IP address: ipv4 or ipv6 literal or a host name. This attribute has been deprecated. Use host instead

'host' (string, default='127.0.0.1', `CREATE`)::
  IP address: ipv4 or ipv6 literal or a host name

'port' (string, default='amqp', `CREATE`)::
  Port number or symbolic service name.

'protocolFamily' (One of ['IPv4', 'IPv6'], `CREATE`)::
  ['IPv4', 'IPv6'] IPv4: Internet Protocol version 4; IPv6: Internet Protocol version 6.  If not specified, the protocol family will be automatically determined from the address.

'role' (One of ['normal', 'inter-router', 'route-container', 'on-demand'], default='normal', `CREATE`)::
  The role of an established connection. In the normal role, the connection is assumed to be used for AMQP clients that are doing normal message delivery over the connection.  In the inter-router role, the connection is assumed to be to another router in the network.  Inter-router discovery and routing protocols can only be used over inter-router connections. route-container role can be used for router-container connections, for example, a router-broker connection. on-demand role has been deprecated.

'cost' (integer, default='1', `CREATE`)::
  For the 'inter-router' role only.  This value assigns a cost metric to the inter-router connection.  The default (and minimum) value is one.  Higher values represent higher costs.  The cost is used to influence the routing algorithm as it attempts to use the path with the lowest total cost from ingress to egress.

'certDb' (path, `CREATE`)::
  The absolute path to the database that contains the public certificates of trusted certificate authorities (CA).

'certFile' (path, `CREATE`)::
  The absolute path to the file containing the PEM-formatted public certificate to be used on the local end of any connections using this profile.

'keyFile' (path, `CREATE`)::
  The absolute path to the file containing the PEM-formatted private key for the above certificate.

'passwordFile' (path, `CREATE`)::
  If the above private key is password protected, this is the absolute path to a file containing the password that unlocks the certificate key.

'password' (string, `CREATE`)::
  An alternative to storing the password in a file referenced by passwordFile is to supply the password right here in the configuration file.  This option can be used by supplying the password in the 'password' option.  Don't use both password and passwordFile in the same profile.

'uidFormat' (string, `CREATE`)::
  A list of x509 client certificate fields that will be used to build a string that will uniquely identify the client certificate owner. For e.g. a value of 'cou' indicates that the uid will consist of c - common name concatenated with o - organization-company name concatenated with u - organization unit; or a value of 'o2' indicates that the uid will consist of o (organization name) concatenated with 2 (the sha256 fingerprint of the entire certificate) . Allowed values can be any combination of 'c'( ISO3166 two character country code), 's'(state or province), 'l'(Locality; generally - city), 'o'(Organization - Company Name), 'u'(Organization Unit - typically certificate type or brand), 'n'(CommonName - typically a user name for client certificates) and '1'(sha1 certificate fingerprint, as displayed in the fingerprints section when looking at a certificate with say a web browser is the hash of the entire certificate) and 2 (sha256 certificate fingerprint) and 5 (sha512 certificate fingerprint). 

'displayNameFile' (string, `CREATE`)::
  The absolute path to the file containing the unique id to dispay name mapping

'sslProfileName' (string)::
  The name of the ssl profile. This is for internal use only. Use the 'name' attribute to assign a name to an sslProfile section 

'saslMechanisms' (string, `CREATE`)::
  Space separated list of accepted SASL authentication mechanisms.

'allowRedirect' (boolean, default=True, `CREATE`)::
  Allow the peer to redirect this connection to another address.

'maxFrameSize' (integer, default=65536, `CREATE`)::
  Maximum frame size in octets that will be used in the connection-open negotiation with a connected peer.  The frame size is the largest contiguous set of uninterrupted data that can be sent for a message delivery over the connection. Interleaving of messages on different links is done at frame granularity.

'idleTimeoutSeconds' (integer, default=16, `CREATE`)::
  The idle timeout, in seconds, for connections through this connector.  If no frames are received on the connection for this time interval, the connection shall be closed.

'stripAnnotations' (One of ['in', 'out', 'both', 'no'], default='both', `CREATE`)::
  ['in', 'out', 'both', 'no'] in: Strip the dispatch router specific annotations only on ingress; out: Strip the dispatch router specific annotations only on egress; both: Strip the dispatch router specific annotations on both ingress and egress; no - do not strip dispatch router specific annotations

'linkCapacity' (integer, `CREATE`)::
  The capacity of links within this connection, in terms of message deliveries.  The capacity is the number of messages that can be in-flight concurrently for each link.

'verifyHostName' (boolean, default=True, `CREATE`)::
  yes: Ensures that when initiating a connection (as a client) the host name in the URL to which this connector connects to matches the host name in the digital certificate that the peer sends back as part of the SSL connection; no: Does not perform host name verification

'saslUsername' (string, `CREATE`)::
  The user name that the connector is using to connect to a peer.

'saslPassword' (string, `CREATE`)::
  The password that the connector is using to connect to a peer.


=== log

Configure logging for a particular module. You can use the `UPDATE` operation to change log settings while the router is running.

Operations allowed: `UPDATE`, `READ`



'module' (One of ['ROUTER', 'ROUTER_CORE', 'ROUTER_HELLO', 'ROUTER_LS', 'ROUTER_MA', 'MESSAGE', 'SERVER', 'AGENT', 'CONTAINER', 'ERROR', 'POLICY', 'DEFAULT'], required, `UPDATE`)::
  Module to configure. The special module 'DEFAULT' specifies defaults for all modules.

'enable' (string, `UPDATE`)::
  Levels are: trace, debug, info, notice, warning, error, critical. The enable string is a comma-separated list of levels. A level may have a trailing '\+' to enable that level and above. For example 'trace,debug,warning+' means enable trace, debug, warning, error and critical. The value 'none' means disable logging for the module.

'timestamp' (boolean, `UPDATE`)::
  Include timestamp in log messages.

'source' (boolean, `UPDATE`)::
  Include source file and line number in log messages.

'output' (string, `UPDATE`)::
  Where to send log messages. Can be 'stderr', 'stdout', 'syslog' or a file name.


=== fixedAddress

(DEPRECATED) Establishes treatment for addresses starting with a prefix. This entity has been deprecated. Use address instead

Operations allowed: `CREATE`, `READ`



'prefix' (string, required, `CREATE`)::
  The address prefix (always starting with '/').

'phase' (integer, `CREATE`)::
  The phase of a multi-hop address passing through one or more waypoints.

'fanout' (One of ['multiple', 'single'], default='multiple', `CREATE`)::
  One of 'multiple' or 'single'.  Multiple fanout is a non-competing pattern.  If there are multiple consumers using the same address, each consumer will receive its own copy of every message sent to the address.  Single fanout is a competing pattern where each message is sent to only one consumer.

'bias' (One of ['closest', 'spread'], default='closest', `CREATE`)::
  Only if fanout is single.  One of 'closest' or 'spread'.  Closest bias means that messages to an address will always be delivered to the closest (lowest cost) subscribed consumer. Spread bias will distribute the messages across subscribers in an approximately even manner.


=== waypoint

(DEPRECATED) A remote node that messages for an address pass through. This entity has been deprecated. Use autoLink instead

Operations allowed: `CREATE`, `DELETE`, `READ`



'address' (string, required, `CREATE`)::
  The AMQP address of the waypoint.

'connector' (string, required, `CREATE`)::
  The name of the on-demand connector used to reach the waypoint's container.

'inPhase' (integer, default=-1, `CREATE`)::
  The phase of the address as it is routed _to_ the waypoint.

'outPhase' (integer, default=-1, `CREATE`)::
  The phase of the address as it is routed _from_ the waypoint.


=== linkRoutePattern

(DEPRECATED) An address pattern to match against link sources and targets to cause the router to link-route the attach across the network to a remote node. This entity has been deprecated. Use linkRoute instead

Operations allowed: `CREATE`, `READ`



'prefix' (string, required, `CREATE`)::
  An address prefix to match against target and source addresses.  This pattern must be of the form '<text>.<text1>.<textN>' or '<text>' or '<text>.' and matches any address that contains that prefix.  For example, if the prefix is set to org.apache (or org.apache.), any address that has the prefix 'org.apache'  (like org.apache.dev) will match. Note that a prefix must not start with a (.), can end in a (.) and can contain zero or more dots (.).  Any characters between the dots are simply treated as part of the address

'dir' (One of ['in', 'out', 'both'], default='both', `CREATE`)::
  Link direction for match: 'in' matches only links inbound to the client; 'out' matches only links outbound from the client; 'both' matches any link.

'connector' (string, `CREATE`)::
  The name of the on-demand connector used to reach the target node's container.  If this value is not provided, it means that the target container is expected to be connected to a different router in the network.  This prevents links to a link-routable address from being misinterpreted as message-routing links when there is no route to a valid destination available.


=== address

Entity type for address configuration.  This is used to configure the treatment of message-routed deliveries within a particular address-space.  The configuration controls distribution and address phasing.

Operations allowed: `CREATE`, `DELETE`, `READ`



'prefix' (string, required, `CREATE`)::
  The address prefix for the configured settings

'distribution' (One of ['multicast', 'closest', 'balanced'], default='balanced', `CREATE`)::
  Treatment of traffic associated with the address

'waypoint' (boolean, `CREATE`)::
  Designates this address space as being used for waypoints.  This will cause the proper address-phasing to be used.

'ingressPhase' (integer, `CREATE`)::
  Advanced - Override the ingress phase for this address

'egressPhase' (integer, `CREATE`)::
  Advanced - Override the egress phase for this address


=== linkRoute

Entity type for link-route configuration.  This is used to identify remote containers that shall be destinations for routed link-attaches.  The link-routing configuration applies to an addressing space defined by a prefix.

Operations allowed: `CREATE`, `DELETE`, `READ`



'prefix' (string, required, `CREATE`)::
  The address prefix for the configured settings

'containerId' (string, `CREATE`)::
  ContainerID for the target container

'connection' (string, `CREATE`)::
  The name from a connector or listener

'distribution' (One of ['linkBalanced'], default='linkBalanced', `CREATE`)::
  Treatment of traffic associated with the address

'dir' (One of ['in', 'out'], required, `CREATE`)::
  The permitted direction of links: 'in' means client senders; 'out' means client receivers

'operStatus' (One of ['inactive', 'active'])::
  The operational status of this linkRoute: inactive - The remote container is not connected; active - the remote container is connected and ready to accept link routed attachments.


=== autoLink

Entity type for configuring auto-links.  Auto-links are links whose lifecycle is managed by the router.  These are typically used to attach to waypoints on remote containers (brokers, etc.).

Operations allowed: `CREATE`, `DELETE`, `READ`



'addr' (string, required, `CREATE`)::
  The address of the provisioned object

'dir' (One of ['in', 'out'], required, `CREATE`)::
  The direction of the link to be created.  In means into the router, out means out of the router.

'phase' (integer, `CREATE`)::
  The address phase for this link.  Defaults to '0' for 'out' links and '1' for 'in' links.

'containerId' (string, `CREATE`)::
  ContainerID for the target container

'connection' (string, `CREATE`)::
  The name from a connector or listener

'linkRef' (string)::
  Reference to the org.apache.qpid.dispatch.router.link if the link exists

'operStatus' (One of ['inactive', 'attaching', 'failed', 'active', 'quiescing', 'idle'])::
  The operational status of this autoLink: inactive - The remote container is not connected; attaching - the link is attaching to the remote node; failed - the link attach failed; active - the link is attached and operational; quiescing - the link is transitioning to idle state; idle - the link is attached but there are no deliveries flowing and no unsettled deliveries.

'lastError' (string)::
  The error description from the last attach failure


=== console

Start a websocket/tcp proxy and http file server to serve the web console

Operations allowed: `READ`



'listener' (string)::
  The name of the listener to send the proxied tcp traffic to.

'wsport' (integer, default=5673)::
  port on which to listen for websocket traffic

'proxy' (string)::
  The full path to the proxy program to run.

'home' (string)::
  The full path to the html/css/js files for the console.

'args' (string)::
  Optional args to pass the proxy program for logging, authentication, etc.


=== policy

Defines global connection limit

Operations allowed: `READ`



'maximumConnections' (integer, `CREATE`)::
  Global maximum number of concurrent client connections allowed. Zero implies no limit. This limit is always enforced even if no other policy settings have been defined.

'enableAccessRules' (boolean, `CREATE`)::
  Enable user rule set processing and connection denial.

'policyFolder' (path, `CREATE`)::
  The absolute path to a folder that holds policyRuleset definition .json files. For a small system the rulesets may all be defined in this file. At a larger scale it is better to have the policy files in their own folder and to have none of the rulesets defined here. All rulesets in all .json files in this folder are processed.

'defaultApplication' (string, `CREATE`)::
  Application policyRuleset to use for connections with no open.hostname or a hostname that does not match any existing policy. For users that don't wish to use open.hostname or any multi-tennancy feature, this default policy can be the only policy in effect for the network.

'defaultApplicationEnabled' (boolean, `CREATE`)::
  Enable defaultApplication policy fallback logic.

'connectionsProcessed' (integer)::

'connectionsDenied' (integer)::

'connectionsCurrent' (integer)::


=== policyRuleset

Per application definition of the locations from which users may connect and the groups to which users belong.

Operations allowed: `CREATE`, `READ`



'applicationName' (string, required)::
  The application name.

'maxConnections' (integer, `CREATE`)::
  Maximum number of concurrent client connections allowed. Zero implies no limit.

'maxConnPerUser' (integer, `CREATE`)::
  Maximum number of concurrent client connections allowed for any single user. Zero implies no limit.

'maxConnPerHost' (integer, `CREATE`)::
  Maximum number of concurrent client connections allowed for any remote host. Zero implies no limit.

'userGroups' (map, `CREATE`)::
  A map where each key is a user group name and the corresponding value is a CSV string naming the users in that group. Users who are assigned to one or more groups are deemed 'restricted'. Restricted users are subject to connection ingress policy and are assigned policy settings based on the assigned user groups. Unrestricted users may be allowed or denied. If unrestricted users are allowed to connect then they are assigned to user group default.

'ingressHostGroups' (map, `CREATE`)::
  A map where each key is an ingress host group name and the corresponding value is a CSV string naming the IP addresses or address ranges in that group. IP addresses may be FQDN strings or numeric IPv4 or IPv6 host addresses. A host range is two host addresses of the same address family separated with a hyphen.  The wildcard host address '*' represents any host address.

'ingressPolicies' (map, `CREATE`)::
  A map where each key is a user group name and the corresponding value is a CSV string naming the ingress host group names that restrict the ingress host for the user group. Users who are members of the user group are allowed to connect only from a host in one of the named ingress host groups.

'connectionAllowDefault' (boolean, `CREATE`)::
  Unrestricted users, those who are not members of a defined user group, are allowed to connect to this application. Unrestricted users are assigned to the 'default' user group and receive 'default' settings.

'settings' (map, `CREATE`)::
  A map where each key is a user group name and the value is a map of the corresponding settings for that group.


== Operational Entities


Operational entities provide statistics and other run-time attributes of the router.
The `qdstat(8)` tool provides a convenient way to query run-time statistics.
You can also use the general-purpose management tool `qdmanage(8)` to query
operational attributes.


=== org.amqp.management

The standard AMQP management node interface.

Operations allowed: `QUERY`, `GET-TYPES`, `GET-ANNOTATIONS`, `GET-OPERATIONS`, `GET-ATTRIBUTES`, `GET-MGMT-NODES`, `READ`




==== Operation GET-TYPES

Get the set of entity types and their inheritance relationships

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is the list of the entity types (strings) that it extends.


==== Operation GET-ATTRIBUTES

Get the set of entity types and the annotations they implement

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is a list (of strings) of attributes on that entity type.


==== Operation GET-OPERATIONS

Get the set of entity types and the operations they support

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is the list of operation names (strings) that it supports.


==== Operation GET-ANNOTATIONS

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is the list of annotations (strings) that it  implements.


==== Operation QUERY

Query for attribute values of multiple entities.

.Request body (map)

A map containing the key `attributeNames` with value a list of (string) attribute names to return. If the list or the map is empty or the body is missing all attributes are returned.

.Request properties

'count' (integer)::
  If set, specifies the number of entries from the result set to return. If not set return all from `offset`

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

'offset' (integer)::
  If set, specifies the number of the first element of the result set to be returned.

.Response body (map)

A map with two entries. `attributeNames` is a list of the attribute names returned. `results` is a list of lists each containing the attribute values for a single entity in the same order as the names in the `attributeNames` entry. If an attribute name is not applicable for an entity then the corresponding value is `null`

.Response properties

'count' (integer)::
  Number of results returned

'identity' (string)::
  Set to the value `self`


==== Operation GET-MGMT-NODES

Get the addresses of all management nodes known to this router

.Request properties

'identity' (string)::
  Set to the value `self`

.Response body (list)

A list of addresses (strings) of management nodes known to this management node.


=== management

Qpid dispatch router extensions to the standard org.amqp.management interface.

Operations allowed: `GET-SCHEMA`, `GET-JSON-SCHEMA`, `GET-LOG`, `PROFILE`, `QUERY`, `GET-TYPES`, `GET-ANNOTATIONS`, `GET-OPERATIONS`, `GET-ATTRIBUTES`, `GET-MGMT-NODES`, `READ`




==== Operation GET-SCHEMA-JSON

Get the qdrouterd schema for this router in JSON format

.Request properties

'indent' (integer)::
  Number of spaces to indent the formatted result. If not specified, the result is in minimal format, no unnecessary spaces or newlines.

'identity' (string)::
  Set to the value `self`

.Response body (string)

The qdrouter schema as a JSON string.


==== Operation GET-LOG

Get recent log entries from the router.

.Request properties

'limit' (integer)::
  Maximum number of log entries to get.

'identity' (string)::
  Set to the value `self`

.Response body (string)

A list of log entries where each entry is a list of: module name(string), level name(string), message text(string), file name(string or None), line number(integer or None) , timestamp(integer)


==== Operation GET-SCHEMA

Get the qdrouterd schema for this router in AMQP map format

.Request properties

'identity' (string)::
  Set to the value `self`

.Response body (map)

The qdrouter schema as a map.


=== router.link

Link to another AMQP endpoint: router node, client or other AMQP process.

Operations allowed: `UPDATE`, `READ`



'adminStatus' (One of ['enabled', 'disabled'], default='enabled', `UPDATE`)::

'operStatus' (One of ['up', 'down', 'quiescing', 'idle'])::

'linkName' (string)::
  Name assigned to the link in the Attach.

'linkType' (One of ['endpoint', 'router-control', 'inter-router'])::
  Type of link: endpoint: a link to a normally connected endpoint; inter-router: a link to another router in the network.

'linkDir' (One of ['in', 'out'])::
  Direction of delivery flow over the link, inbound or outbound to or from the router.

'owningAddr' (string)::
  Address assigned to this link during attach: The target for inbound links or the source for outbound links.

'capacity' (integer)::
  The capacity, in deliveries, for the link.  The number of undelivered plus unsettled deliveries shall not exceed the capacity.  This is enforced by link flow control.

'peer' (string)::
  Identifier of the paired link if this is an attach-routed link.

'undeliveredCount' (integer)::
  The number of undelivered messages pending for the link.

'unsettledCount' (integer)::
  The number of unsettled deliveries awaiting settlement on the link

'deliveryCount' (integer)::
  The total number of deliveries that have traversed this link.


=== router.address

AMQP address managed by the router.

Operations allowed: `READ`



'distribution' (One of ['flood', 'multicast', 'closest', 'balanced', 'linkBalanced'])::
  Forwarding treatment for the address: flood - messages delivered to all subscribers along all available paths (this will cause duplicate deliveries if there are redundant paths); multi - one copy of each message delivered to all subscribers; anyClosest - messages delivered to only the closest subscriber; anyBalanced - messages delivered to one subscriber with load balanced across subscribers; linkBalanced - for link-routing, link attaches balanced across destinations.

'inProcess' (integer)::
  The number of in-process subscribers for this address

'subscriberCount' (integer)::
  The number of local subscribers for this address (i.e. attached to this router)

'remoteCount' (integer)::
  The number of remote routers that have at least one subscriber to this address

'containerCount' (integer)::
  The number of attached containers that serve this route address

'deliveriesIngress' (integer)::
  The number of deliveries to this address that entered the router network on this router

'deliveriesEgress' (integer)::
  The number of deliveries to this address that exited the router network on this router

'deliveriesTransit' (integer)::
  The number of deliveries to this address that transited this router to another router

'deliveriesToContainer' (integer)::
  The number of deliveries to this address that were given to an in-process subscriber

'deliveriesFromContainer' (integer)::
  The number of deliveries to this address that were originated from an in-process entity

'key' (string)::
  Internal unique (to this router) key to identify the address

'remoteHostRouters' (list)::
  List of remote routers on which there is a destination for this address.

'transitOutstanding' (list)::
  List of numbers of outstanding deliveries across a transit (inter-router) link for this address.  This is for balanced distribution only.

'trackedDeliveries' (integer)::
  Number of transit deliveries being tracked for this address (for balanced distribution).


=== router.node

Remote router node connected to this router.

Operations allowed: `READ`



'id' (string)::
  Remote node identifier.

'instance' (integer)::
  Remote node boot number.

'linkState' (list)::
  List of remote node's neighbours.

'nextHop' (string)::
  Neighbour ID of next hop to remote node from here.

'validOrigins' (list)::
  List of valid origin nodes for messages arriving via the re mote node, used for duplicate elimination in redundant networks.

'address' (string)::
  Address of the remote node

'routerLink' (entityId)::
  Local link to remote node

'cost' (integer)::
  Reachability cost


=== connection

Connections to the router's container.

Operations allowed: `READ`



'container' (string)::
  The container for this connection

'opened' (boolean)::
  The connection has been opened (i.e. AMQP OPEN)

'host' (string)::
  IP address and port number in the form addr:port.

'dir' (One of ['in', 'out'])::
  Direction of connection establishment in or out of the router.

'role' (string)::

'isAuthenticated' (boolean)::
  Indicates whether the identity of the connection's user is authentic.

'isEncrypted' (boolean)::
  Indicates whether the connection content is encrypted.

'sasl' (string)::
  SASL mechanism in effect for authentication.

'user' (string)::
  Identity of the authenticated user.

'ssl' (boolean)::
  True iff SSL/TLS is in effect for this connection.

'sslProto' (string)::
  SSL protocol name

'sslCipher' (string)::
  SSL cipher name

'sslSsf' (integer)::
  SSL strength factor in effect

'properties' (map)::
  Connection properties supplied by the peer.


=== allocator

Memory allocation pool.

Operations allowed: `READ`



'typeName' (string)::

'typeSize' (integer)::

'transferBatchSize' (integer)::

'localFreeListMax' (integer)::

'globalFreeListMax' (integer)::

'totalAllocFromHeap' (integer)::

'totalFreeToHeap' (integer)::

'heldByThreads' (integer)::

'batchesRebalancedToThreads' (integer)::

'batchesRebalancedToGlobal' (integer)::


=== policyStats

Per application connection and access statistics.

Operations allowed: `READ`



'applicationName' (string)::
  The application name.

'connectionsApproved' (integer)::

'connectionsDenied' (integer)::

'connectionsCurrent' (integer)::

'perUserState' (map)::
  A map where the key is the authenticated user name and the value is a list of the user's connections.

'perHostState' (map)::
  A map where the key is the host name and the value is a list of the host's connections.

'sessionDenied' (integer)::

'senderDenied' (integer)::

'receiverDenied' (integer)::


== Management Operations


The 'qdstat(8)' and 'qdmanage(8)' tools allow you to view or modify management entity
attributes. They work by invoking *management operations*. You can invoke these operations
from any AMQP client by sending a message with the appropriate properties and body to the
'$management' address. The message should have a 'reply-to' address indicating where the
response should be sent.


=== Operations for all entity types


==== Operation READ

Read attributes of a single entity

.Request properties

'type' (string)::
  Type of desired entity.

'name' (string)::
  Name of desired entity. Must supply name or identity.

'identity' (string)::
  Identity of desired entity. Must supply name or identity.

.Response body (map)

Attributes of the entity


==== Operation CREATE

Create a new entity.

.Request body (map, required)

Attributes for the new entity. Can include name and/or type.

.Request properties

'type' (string, required)::
  Type of new entity.

'name' (string)::
  Name of new entity. Optional, defaults to identity.

.Response body (map)

Attributes of the entity


==== Operation UPDATE

Update attributes of an entity

.Request body (map)

Attributes to update for the entity. Can include name or identity.

.Request properties

'type' (string)::
  Type of desired entity.

'name' (string)::
  Name of desired entity. Must supply name or identity.

'identity' (string)::
  Identity of desired entity. Must supply name or identity.

.Response body (map)

Updated attributes of the entity


==== Operation DELETE

Delete an entity

.Request properties

'type' (string)::
  Type of desired entity.

'name' (string)::
  Name of desired entity. Must supply name or identity.

'identity' (string)::
  Identity of desired entity. Must supply name or identity.


=== Operations for 'org.amqp.management' entity type


==== Operation GET-TYPES

Get the set of entity types and their inheritance relationships

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is the list of the entity types (strings) that it extends.


==== Operation GET-ATTRIBUTES

Get the set of entity types and the annotations they implement

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is a list (of strings) of attributes on that entity type.


==== Operation GET-OPERATIONS

Get the set of entity types and the operations they support

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is the list of operation names (strings) that it supports.


==== Operation GET-ANNOTATIONS

.Request properties

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

.Response body (map)

A map where each key is an entity type name (string) and the corresponding value is the list of annotations (strings) that it  implements.


==== Operation QUERY

Query for attribute values of multiple entities.

.Request body (map)

A map containing the key `attributeNames` with value a list of (string) attribute names to return. If the list or the map is empty or the body is missing all attributes are returned.

.Request properties

'count' (integer)::
  If set, specifies the number of entries from the result set to return. If not set return all from `offset`

'entityType' (string)::
  If set, restrict query results to entities that extend (directly or indirectly) this type

'identity' (string)::
  Set to the value `self`

'offset' (integer)::
  If set, specifies the number of the first element of the result set to be returned.

.Response body (map)

A map with two entries. `attributeNames` is a list of the attribute names returned. `results` is a list of lists each containing the attribute values for a single entity in the same order as the names in the `attributeNames` entry. If an attribute name is not applicable for an entity then the corresponding value is `null`

.Response properties

'count' (integer)::
  Number of results returned

'identity' (string)::
  Set to the value `self`


==== Operation GET-MGMT-NODES

Get the addresses of all management nodes known to this router

.Request properties

'identity' (string)::
  Set to the value `self`

.Response body (list)

A list of addresses (strings) of management nodes known to this management node.


=== Operations for 'management' entity type


==== Operation GET-SCHEMA-JSON

Get the qdrouterd schema for this router in JSON format

.Request properties

'indent' (integer)::
  Number of spaces to indent the formatted result. If not specified, the result is in minimal format, no unnecessary spaces or newlines.

'identity' (string)::
  Set to the value `self`

.Response body (string)

The qdrouter schema as a JSON string.


==== Operation GET-LOG

Get recent log entries from the router.

.Request properties

'limit' (integer)::
  Maximum number of log entries to get.

'identity' (string)::
  Set to the value `self`

.Response body (string)

A list of log entries where each entry is a list of: module name(string), level name(string), message text(string), file name(string or None), line number(integer or None) , timestamp(integer)


==== Operation GET-SCHEMA

Get the qdrouterd schema for this router in AMQP map format

.Request properties

'identity' (string)::
  Set to the value `self`

.Response body (map)

The qdrouter schema as a map.

